import type { TemplateFamily } from "../types.js";

const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;
const MARGIN = 54;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2; // 504

export const FORMA_EDITORIAL_REPORT: TemplateFamily = {
  version: "1.0",
  id: "forma-editorial-report",
  name: "Forma Editorial Report",
  description:
    "A clean, authoritative multi-page report template family with refined typography, balanced whitespace, and data-dense editorial layouts.",
  family: "document",
  varietyRules: {
    cover: { visualDensity: "low", visualType: "section", repeatLimit: 1 },
    "section-opener": {
      visualDensity: "low",
      visualType: "section",
      repeatLimit: 1,
    },
    "heading-body": {
      visualDensity: "medium",
      visualType: "editorial",
      repeatLimit: 2,
    },
    "heading-image-body": {
      visualDensity: "medium",
      visualType: "image",
      repeatLimit: 2,
    },
    "two-column-body": {
      visualDensity: "high",
      visualType: "editorial",
      repeatLimit: 2,
    },
    "three-stat": {
      visualDensity: "medium",
      visualType: "data",
      repeatLimit: 1,
      avoidFollowingTypes: ["data"],
    },
    "four-stat": {
      visualDensity: "high",
      visualType: "data",
      repeatLimit: 1,
      avoidFollowingTypes: ["data"],
    },
    "quote-feature": {
      visualDensity: "low",
      visualType: "quote",
      repeatLimit: 1,
    },
    "table-page": {
      visualDensity: "high",
      visualType: "table",
      repeatLimit: 2,
    },
    "chart-commentary": {
      visualDensity: "medium",
      visualType: "data",
      repeatLimit: 1,
    },
    closing: { visualDensity: "low", visualType: "section", repeatLimit: 1 },
  },
  pageSize: {
    width: PAGE_WIDTH,
    height: PAGE_HEIGHT,
    unit: "pt",
  },
  designTokens: {
    colors: {
      primary: "#0f172a", // Deep navy/slate
      secondary: "#334155", // Slate body
      muted: "#64748b", // Subtle metadata/caption
      background: "#ffffff",
      surface: "#f8fafc",
      accent: "#2563eb", // Royal blue accent
      border: "#e2e8f0",
      accentSubtle: "#eff6ff",
    },
    typography: {
      title: {
        fontFamily: "Playfair Display",
        fontSize: 34,
        fontWeight: 700,
        lineHeight: 1.2,
        color: "#0f172a",
      },
      subtitle: {
        fontFamily: "Inter",
        fontSize: 16,
        fontWeight: 400,
        lineHeight: 1.4,
        color: "#475569",
      },
      sectionHeading: {
        fontFamily: "Playfair Display",
        fontSize: 26,
        fontWeight: 700,
        lineHeight: 1.25,
        color: "#0f172a",
      },
      heading: {
        fontFamily: "Inter",
        fontSize: 20,
        fontWeight: 600,
        lineHeight: 1.3,
        color: "#0f172a",
      },
      subheading: {
        fontFamily: "Inter",
        fontSize: 14,
        fontWeight: 600,
        lineHeight: 1.4,
        color: "#334155",
      },
      body: {
        fontFamily: "Inter",
        fontSize: 11,
        fontWeight: 400,
        lineHeight: 1.6,
        color: "#334155",
      },
      bodyLarge: {
        fontFamily: "Inter",
        fontSize: 13,
        fontWeight: 400,
        lineHeight: 1.6,
        color: "#334155",
      },
      statNumber: {
        fontFamily: "Playfair Display",
        fontSize: 38,
        fontWeight: 700,
        lineHeight: 1.1,
        color: "#2563eb",
      },
      statLabel: {
        fontFamily: "Inter",
        fontSize: 11,
        fontWeight: 600,
        lineHeight: 1.3,
        color: "#0f172a",
      },
      statDescription: {
        fontFamily: "Inter",
        fontSize: 10,
        fontWeight: 400,
        lineHeight: 1.4,
        color: "#64748b",
      },
      quote: {
        fontFamily: "Playfair Display",
        fontSize: 20,
        fontWeight: 500,
        lineHeight: 1.45,
        color: "#0f172a",
      },
      attribution: {
        fontFamily: "Inter",
        fontSize: 11,
        fontWeight: 500,
        lineHeight: 1.4,
        color: "#64748b",
      },
      caption: {
        fontFamily: "Inter",
        fontSize: 9,
        fontWeight: 400,
        lineHeight: 1.4,
        color: "#94a3b8",
      },
      metadata: {
        fontFamily: "Inter",
        fontSize: 10,
        fontWeight: 500,
        lineHeight: 1.3,
        color: "#64748b",
      },
    },
    spacing: {
      xs: 4,
      sm: 8,
      md: 16,
      lg: 24,
      xl: 36,
      xxl: 54,
    },
    grid: {
      columns: 12,
      margin: MARGIN,
      gutter: 18,
    },
    radii: {
      none: 0,
      sm: 4,
      md: 8,
      lg: 12,
    },
    strokes: {
      thin: 1,
      medium: 2,
    },
    imageTreatment: {
      borderRadius: 6,
      aspectRatio: "16:9",
    },
  },
  layouts: [
    // 1. Cover
    {
      id: "cover",
      name: "Report Cover",
      role: "cover",
      slots: [
        {
          id: "kicker",
          name: "Category / Eyebrow",
          role: "kicker",
          accepts: ["caption", "metadata", "unknown", "paragraph"],
          required: false,
          maxCharacters: 60,
        },
        {
          id: "title",
          name: "Document Title",
          role: "heading",
          accepts: ["heading", "paragraph"],
          required: true,
          maxCharacters: 120,
        },
        {
          id: "subtitle",
          name: "Subtitle / Summary",
          role: "subheading",
          accepts: ["subheading", "paragraph", "callout"],
          required: false,
          maxCharacters: 250,
        },
        {
          id: "metadata",
          name: "Date / Author / Organization",
          role: "attribution",
          accepts: ["metadata", "paragraph", "caption", "unknown"],
          required: false,
          maxCharacters: 100,
        },
      ],
      baseElements: [
        // Decorative top accent bar
        {
          id: "cover-accent-bar",
          type: "shape",
          shape: "rectangle",
          x: MARGIN,
          y: 72,
          width: 48,
          height: 4,
          fill: { color: "#2563eb" },
        },
        {
          id: "cover-kicker",
          type: "text",
          slotId: "kicker",
          x: MARGIN,
          y: 92,
          width: CONTENT_WIDTH,
          height: 24,
          textStyle: {
            fontFamily: "Inter",
            fontSize: 12,
            fontWeight: 600,
            color: "#2563eb",
            letterSpacing: 1.5,
          },
        },
        {
          id: "cover-title",
          type: "text",
          slotId: "title",
          x: MARGIN,
          y: 130,
          width: CONTENT_WIDTH,
          height: 180,
          constraints: {
            minFontSize: 24,
            maxFontSize: 40,
            allowResize: true,
          },
          textStyle: {
            fontFamily: "Playfair Display",
            fontSize: 34,
            fontWeight: 700,
            lineHeight: 1.2,
            color: "#0f172a",
          },
        },
        {
          id: "cover-subtitle",
          type: "text",
          slotId: "subtitle",
          x: MARGIN,
          y: 330,
          width: CONTENT_WIDTH - 40,
          height: 100,
          constraints: {
            minFontSize: 13,
            maxFontSize: 18,
            allowResize: true,
          },
          textStyle: {
            fontFamily: "Inter",
            fontSize: 15,
            fontWeight: 400,
            lineHeight: 1.5,
            color: "#475569",
          },
        },
        // Decorative divider
        {
          id: "cover-divider",
          type: "shape",
          shape: "line",
          x: MARGIN,
          y: 660,
          width: CONTENT_WIDTH,
          height: 1,
          stroke: { color: "#e2e8f0" },
          strokeWidth: 1,
        },
        {
          id: "cover-metadata",
          type: "text",
          slotId: "metadata",
          x: MARGIN,
          y: 678,
          width: CONTENT_WIDTH,
          height: 40,
          textStyle: {
            fontFamily: "Inter",
            fontSize: 10,
            fontWeight: 500,
            color: "#64748b",
            lineHeight: 1.4,
          },
        },
      ],
    },

    // 2. Section Opener
    {
      id: "section-opener",
      name: "Section Opener",
      role: "section",
      fallbackLayouts: ["heading-body"],
      slots: [
        {
          id: "section-label",
          name: "Section Number / Kicker",
          role: "kicker",
          accepts: ["caption", "metadata", "unknown", "heading"],
          required: false,
          maxCharacters: 40,
        },
        {
          id: "section-heading",
          name: "Section Title",
          role: "heading",
          accepts: ["heading", "subheading"],
          required: true,
          maxCharacters: 120,
        },
        {
          id: "section-intro",
          name: "Section Introduction",
          role: "body",
          accepts: ["paragraph", "callout"],
          required: false,
          maxCharacters: 450,
        },
      ],
      baseElements: [
        {
          id: "sec-bg",
          type: "shape",
          shape: "rectangle",
          x: MARGIN,
          y: 120,
          width: CONTENT_WIDTH,
          height: 380,
          fill: { color: "#f8fafc" },
          stroke: { color: "#e2e8f0" },
          strokeWidth: 1,
        },
        {
          id: "sec-label",
          type: "text",
          slotId: "section-label",
          x: MARGIN + 40,
          y: 160,
          width: CONTENT_WIDTH - 80,
          height: 24,
          textStyle: {
            fontFamily: "Inter",
            fontSize: 12,
            fontWeight: 700,
            color: "#2563eb",
            letterSpacing: 2,
          },
        },
        {
          id: "sec-heading",
          type: "text",
          slotId: "section-heading",
          x: MARGIN + 40,
          y: 200,
          width: CONTENT_WIDTH - 80,
          height: 120,
          textStyle: {
            fontFamily: "Playfair Display",
            fontSize: 28,
            fontWeight: 700,
            lineHeight: 1.25,
            color: "#0f172a",
          },
        },
        {
          id: "sec-intro",
          type: "text",
          slotId: "section-intro",
          x: MARGIN + 40,
          y: 330,
          width: CONTENT_WIDTH - 80,
          height: 130,
          textStyle: {
            fontFamily: "Inter",
            fontSize: 12,
            fontWeight: 400,
            lineHeight: 1.6,
            color: "#334155",
          },
        },
      ],
    },

    // 3. Heading + Body (Text Dominant)
    {
      id: "heading-body",
      name: "Text Dominant Article",
      role: "content",
      fallbackLayouts: ["two-column-body"],
      slots: [
        {
          id: "heading",
          name: "Heading",
          role: "heading",
          accepts: ["heading", "subheading"],
          required: true,
          maxCharacters: 120,
        },
        {
          id: "body",
          name: "Body Content",
          role: "body",
          accepts: ["paragraph", "list_item", "callout"],
          required: true,
          maxCharacters: 2400,
          allowOverflow: false,
        },
      ],
      baseElements: [
        {
          id: "hb-heading",
          type: "text",
          slotId: "heading",
          x: MARGIN,
          y: 72,
          width: CONTENT_WIDTH,
          height: 60,
          constraints: {
            minFontSize: 16,
            maxFontSize: 24,
            allowResize: true,
          },
          textStyle: {
            fontFamily: "Playfair Display",
            fontSize: 22,
            fontWeight: 700,
            lineHeight: 1.3,
            color: "#0f172a",
          },
        },
        {
          id: "hb-divider",
          type: "shape",
          shape: "line",
          x: MARGIN,
          y: 138,
          width: CONTENT_WIDTH,
          height: 1,
          stroke: { color: "#e2e8f0" },
          strokeWidth: 1,
        },
        {
          id: "hb-body",
          type: "text",
          slotId: "body",
          x: MARGIN,
          y: 156,
          width: CONTENT_WIDTH,
          height: 570,
          constraints: {
            minFontSize: 9.5,
            maxFontSize: 13,
            allowReflow: true,
            allowResize: true,
          },
          textStyle: {
            fontFamily: "Inter",
            fontSize: 11,
            fontWeight: 400,
            lineHeight: 1.6,
            color: "#334155",
          },
        },
      ],
    },

    // 4. Heading + Image + Body
    {
      id: "heading-image-body",
      name: "Heading, Feature Image & Body",
      role: "content",
      fallbackLayouts: ["heading-body", "two-column-body"],
      slots: [
        {
          id: "heading",
          name: "Heading",
          role: "heading",
          accepts: ["heading", "subheading"],
          required: true,
          maxCharacters: 120,
        },
        {
          id: "image",
          name: "Feature Image",
          role: "image",
          accepts: ["caption", "unknown"],
          required: false,
        },
        {
          id: "caption",
          name: "Image Caption",
          role: "caption",
          accepts: ["caption", "metadata"],
          required: false,
          maxCharacters: 140,
        },
        {
          id: "body",
          name: "Body Content",
          role: "body",
          accepts: ["paragraph", "list_item", "callout"],
          required: true,
          maxCharacters: 1400,
        },
      ],
      baseElements: [
        {
          id: "hib-heading",
          type: "text",
          slotId: "heading",
          x: MARGIN,
          y: 72,
          width: CONTENT_WIDTH,
          height: 56,
          textStyle: {
            fontFamily: "Playfair Display",
            fontSize: 22,
            fontWeight: 700,
            lineHeight: 1.3,
            color: "#0f172a",
          },
        },
        {
          id: "hib-image",
          type: "image",
          slotId: "image",
          assetRef: "default-editorial-placeholder",
          x: MARGIN,
          y: 140,
          width: CONTENT_WIDTH,
          height: 220,
          fit: "crop",
        },
        {
          id: "hib-caption",
          type: "text",
          slotId: "caption",
          x: MARGIN,
          y: 368,
          width: CONTENT_WIDTH,
          height: 20,
          textStyle: {
            fontFamily: "Inter",
            fontSize: 9.5,
            fontWeight: 400,
            color: "#64748b",
            align: "right",
          },
        },
        {
          id: "hib-body",
          type: "text",
          slotId: "body",
          x: MARGIN,
          y: 396,
          width: CONTENT_WIDTH,
          height: 330,
          constraints: {
            minFontSize: 9.5,
            maxFontSize: 12,
            allowResize: true,
          },
          textStyle: {
            fontFamily: "Inter",
            fontSize: 10.5,
            fontWeight: 400,
            lineHeight: 1.6,
            color: "#334155",
          },
        },
      ],
    },

    // 5. Two-column Body
    {
      id: "two-column-body",
      name: "Two-Column Editorial",
      role: "content",
      fallbackLayouts: ["heading-body"],
      slots: [
        {
          id: "heading",
          name: "Main Heading",
          role: "heading",
          accepts: ["heading", "subheading"],
          required: true,
          maxCharacters: 120,
        },
        {
          id: "lead",
          name: "Lead Paragraph",
          role: "body",
          accepts: ["paragraph", "callout"],
          required: false,
          maxCharacters: 350,
        },
        {
          id: "column1",
          name: "Column 1 Text",
          role: "body",
          accepts: ["paragraph", "list_item"],
          required: true,
          maxCharacters: 1200,
        },
        {
          id: "column2",
          name: "Column 2 Text",
          role: "body",
          accepts: ["paragraph", "list_item"],
          required: false,
          maxCharacters: 1200,
        },
      ],
      baseElements: [
        {
          id: "tc-heading",
          type: "text",
          slotId: "heading",
          x: MARGIN,
          y: 72,
          width: CONTENT_WIDTH,
          height: 54,
          textStyle: {
            fontFamily: "Playfair Display",
            fontSize: 22,
            fontWeight: 700,
            lineHeight: 1.3,
            color: "#0f172a",
          },
        },
        {
          id: "tc-lead",
          type: "text",
          slotId: "lead",
          x: MARGIN,
          y: 132,
          width: CONTENT_WIDTH,
          height: 60,
          textStyle: {
            fontFamily: "Inter",
            fontSize: 12.5,
            fontWeight: 500,
            lineHeight: 1.5,
            color: "#1e293b",
          },
        },
        {
          id: "tc-divider",
          type: "shape",
          shape: "line",
          x: MARGIN,
          y: 200,
          width: CONTENT_WIDTH,
          height: 1,
          stroke: { color: "#e2e8f0" },
          strokeWidth: 1,
        },
        {
          id: "tc-col1",
          type: "text",
          slotId: "column1",
          x: MARGIN,
          y: 218,
          width: (CONTENT_WIDTH - 24) / 2, // 240
          height: 500,
          constraints: {
            minFontSize: 9.5,
            maxFontSize: 12,
            allowResize: true,
          },
          textStyle: {
            fontFamily: "Inter",
            fontSize: 10.5,
            fontWeight: 400,
            lineHeight: 1.55,
            color: "#334155",
          },
        },
        {
          id: "tc-col2",
          type: "text",
          slotId: "column2",
          x: MARGIN + (CONTENT_WIDTH - 24) / 2 + 24, // 318
          y: 218,
          width: (CONTENT_WIDTH - 24) / 2, // 240
          height: 500,
          constraints: {
            minFontSize: 9.5,
            maxFontSize: 12,
            allowResize: true,
          },
          textStyle: {
            fontFamily: "Inter",
            fontSize: 10.5,
            fontWeight: 400,
            lineHeight: 1.55,
            color: "#334155",
          },
        },
      ],
    },

    // 6. Three-stat
    {
      id: "three-stat",
      name: "Three Key Statistics",
      role: "stats",
      fallbackLayouts: ["four-stat", "heading-body"],
      slots: [
        {
          id: "heading",
          name: "Section Heading",
          role: "heading",
          accepts: ["heading", "subheading"],
          required: true,
          maxCharacters: 100,
        },
        {
          id: "intro",
          name: "Context Narrative",
          role: "body",
          accepts: ["paragraph", "callout"],
          required: false,
          maxCharacters: 400,
        },
        {
          id: "stat1-value",
          name: "Statistic 1 Value",
          role: "stat_value",
          accepts: ["statistic", "paragraph", "heading"],
          required: true,
          maxCharacters: 30,
        },
        {
          id: "stat1-desc",
          name: "Statistic 1 Label & Description",
          role: "stat_description",
          accepts: ["paragraph", "caption", "list_item", "unknown"],
          required: true,
          maxCharacters: 180,
        },
        {
          id: "stat2-value",
          name: "Statistic 2 Value",
          role: "stat_value",
          accepts: ["statistic", "paragraph", "heading"],
          required: true,
          maxCharacters: 30,
        },
        {
          id: "stat2-desc",
          name: "Statistic 2 Label & Description",
          role: "stat_description",
          accepts: ["paragraph", "caption", "list_item", "unknown"],
          required: true,
          maxCharacters: 180,
        },
        {
          id: "stat3-value",
          name: "Statistic 3 Value",
          role: "stat_value",
          accepts: ["statistic", "paragraph", "heading"],
          required: true,
          maxCharacters: 30,
        },
        {
          id: "stat3-desc",
          name: "Statistic 3 Label & Description",
          role: "stat_description",
          accepts: ["paragraph", "caption", "list_item", "unknown"],
          required: true,
          maxCharacters: 180,
        },
      ],
      baseElements: [
        {
          id: "ts-heading",
          type: "text",
          slotId: "heading",
          x: MARGIN,
          y: 72,
          width: CONTENT_WIDTH,
          height: 56,
          textStyle: {
            fontFamily: "Playfair Display",
            fontSize: 24,
            fontWeight: 700,
            lineHeight: 1.25,
            color: "#0f172a",
          },
        },
        {
          id: "ts-intro",
          type: "text",
          slotId: "intro",
          x: MARGIN,
          y: 136,
          width: CONTENT_WIDTH,
          height: 70,
          textStyle: {
            fontFamily: "Inter",
            fontSize: 12,
            fontWeight: 400,
            lineHeight: 1.55,
            color: "#475569",
          },
        },
        // Card 1
        {
          id: "ts-card1-bg",
          type: "shape",
          shape: "rounded",
          x: MARGIN,
          y: 226,
          width: CONTENT_WIDTH,
          height: 140,
          fill: { color: "#f8fafc" },
          stroke: { color: "#e2e8f0" },
          strokeWidth: 1,
        },
        {
          id: "ts-card1-val",
          type: "text",
          slotId: "stat1-value",
          x: MARGIN + 28,
          y: 250,
          width: 140,
          height: 60,
          textStyle: {
            fontFamily: "Playfair Display",
            fontSize: 36,
            fontWeight: 700,
            color: "#2563eb",
          },
        },
        {
          id: "ts-card1-desc",
          type: "text",
          slotId: "stat1-desc",
          x: MARGIN + 184,
          y: 252,
          width: CONTENT_WIDTH - 212,
          height: 80,
          textStyle: {
            fontFamily: "Inter",
            fontSize: 11,
            fontWeight: 400,
            lineHeight: 1.5,
            color: "#334155",
          },
        },
        // Card 2
        {
          id: "ts-card2-bg",
          type: "shape",
          shape: "rounded",
          x: MARGIN,
          y: 386,
          width: CONTENT_WIDTH,
          height: 140,
          fill: { color: "#f8fafc" },
          stroke: { color: "#e2e8f0" },
          strokeWidth: 1,
        },
        {
          id: "ts-card2-val",
          type: "text",
          slotId: "stat2-value",
          x: MARGIN + 28,
          y: 410,
          width: 140,
          height: 60,
          textStyle: {
            fontFamily: "Playfair Display",
            fontSize: 36,
            fontWeight: 700,
            color: "#2563eb",
          },
        },
        {
          id: "ts-card2-desc",
          type: "text",
          slotId: "stat2-desc",
          x: MARGIN + 184,
          y: 412,
          width: CONTENT_WIDTH - 212,
          height: 80,
          textStyle: {
            fontFamily: "Inter",
            fontSize: 11,
            fontWeight: 400,
            lineHeight: 1.5,
            color: "#334155",
          },
        },
        // Card 3
        {
          id: "ts-card3-bg",
          type: "shape",
          shape: "rounded",
          x: MARGIN,
          y: 546,
          width: CONTENT_WIDTH,
          height: 140,
          fill: { color: "#f8fafc" },
          stroke: { color: "#e2e8f0" },
          strokeWidth: 1,
        },
        {
          id: "ts-card3-val",
          type: "text",
          slotId: "stat3-value",
          x: MARGIN + 28,
          y: 570,
          width: 140,
          height: 60,
          textStyle: {
            fontFamily: "Playfair Display",
            fontSize: 36,
            fontWeight: 700,
            color: "#2563eb",
          },
        },
        {
          id: "ts-card3-desc",
          type: "text",
          slotId: "stat3-desc",
          x: MARGIN + 184,
          y: 572,
          width: CONTENT_WIDTH - 212,
          height: 80,
          textStyle: {
            fontFamily: "Inter",
            fontSize: 11,
            fontWeight: 400,
            lineHeight: 1.5,
            color: "#334155",
          },
        },
      ],
    },

    // 7. Four-stat
    {
      id: "four-stat",
      name: "Four Statistics Grid",
      role: "stats",
      fallbackLayouts: ["three-stat", "heading-body"],
      slots: [
        {
          id: "heading",
          name: "Section Heading",
          role: "heading",
          accepts: ["heading", "subheading"],
          required: true,
          maxCharacters: 100,
        },
        {
          id: "intro",
          name: "Introduction",
          role: "body",
          accepts: ["paragraph", "callout"],
          required: false,
          maxCharacters: 300,
        },
        {
          id: "stat1-value",
          name: "Stat 1 Value",
          role: "stat_value",
          accepts: ["statistic", "paragraph", "heading"],
          required: true,
          maxCharacters: 25,
        },
        {
          id: "stat1-desc",
          name: "Stat 1 Label & Description",
          role: "stat_description",
          accepts: ["paragraph", "caption", "list_item", "unknown"],
          required: true,
          maxCharacters: 140,
        },
        {
          id: "stat2-value",
          name: "Stat 2 Value",
          role: "stat_value",
          accepts: ["statistic", "paragraph", "heading"],
          required: true,
          maxCharacters: 25,
        },
        {
          id: "stat2-desc",
          name: "Stat 2 Label & Description",
          role: "stat_description",
          accepts: ["paragraph", "caption", "list_item", "unknown"],
          required: true,
          maxCharacters: 140,
        },
        {
          id: "stat3-value",
          name: "Stat 3 Value",
          role: "stat_value",
          accepts: ["statistic", "paragraph", "heading"],
          required: true,
          maxCharacters: 25,
        },
        {
          id: "stat3-desc",
          name: "Stat 3 Label & Description",
          role: "stat_description",
          accepts: ["paragraph", "caption", "list_item", "unknown"],
          required: true,
          maxCharacters: 140,
        },
        {
          id: "stat4-value",
          name: "Stat 4 Value",
          role: "stat_value",
          accepts: ["statistic", "paragraph", "heading"],
          required: true,
          maxCharacters: 25,
        },
        {
          id: "stat4-desc",
          name: "Stat 4 Label & Description",
          role: "stat_description",
          accepts: ["paragraph", "caption", "list_item", "unknown"],
          required: true,
          maxCharacters: 140,
        },
      ],
      baseElements: [
        {
          id: "fs-heading",
          type: "text",
          slotId: "heading",
          x: MARGIN,
          y: 72,
          width: CONTENT_WIDTH,
          height: 52,
          textStyle: {
            fontFamily: "Playfair Display",
            fontSize: 24,
            fontWeight: 700,
            lineHeight: 1.25,
            color: "#0f172a",
          },
        },
        {
          id: "fs-intro",
          type: "text",
          slotId: "intro",
          x: MARGIN,
          y: 132,
          width: CONTENT_WIDTH,
          height: 50,
          textStyle: {
            fontFamily: "Inter",
            fontSize: 11.5,
            fontWeight: 400,
            lineHeight: 1.5,
            color: "#475569",
          },
        },
        // Quadrant 1 (top-left)
        {
          id: "fs-card1-bg",
          type: "shape",
          shape: "rounded",
          x: MARGIN,
          y: 204,
          width: (CONTENT_WIDTH - 20) / 2, // 242
          height: 220,
          fill: { color: "#f8fafc" },
          stroke: { color: "#e2e8f0" },
          strokeWidth: 1,
        },
        {
          id: "fs-card1-val",
          type: "text",
          slotId: "stat1-value",
          x: MARGIN + 20,
          y: 224,
          width: (CONTENT_WIDTH - 20) / 2 - 40,
          height: 48,
          textStyle: {
            fontFamily: "Playfair Display",
            fontSize: 34,
            fontWeight: 700,
            color: "#2563eb",
          },
        },
        {
          id: "fs-card1-desc",
          type: "text",
          slotId: "stat1-desc",
          x: MARGIN + 20,
          y: 280,
          width: (CONTENT_WIDTH - 20) / 2 - 40,
          height: 120,
          textStyle: {
            fontFamily: "Inter",
            fontSize: 10.5,
            fontWeight: 400,
            lineHeight: 1.5,
            color: "#334155",
          },
        },
        // Quadrant 2 (top-right)
        {
          id: "fs-card2-bg",
          type: "shape",
          shape: "rounded",
          x: MARGIN + (CONTENT_WIDTH - 20) / 2 + 20, // 316
          y: 204,
          width: (CONTENT_WIDTH - 20) / 2, // 242
          height: 220,
          fill: { color: "#f8fafc" },
          stroke: { color: "#e2e8f0" },
          strokeWidth: 1,
        },
        {
          id: "fs-card2-val",
          type: "text",
          slotId: "stat2-value",
          x: MARGIN + (CONTENT_WIDTH - 20) / 2 + 40,
          y: 224,
          width: (CONTENT_WIDTH - 20) / 2 - 40,
          height: 48,
          textStyle: {
            fontFamily: "Playfair Display",
            fontSize: 34,
            fontWeight: 700,
            color: "#2563eb",
          },
        },
        {
          id: "fs-card2-desc",
          type: "text",
          slotId: "stat2-desc",
          x: MARGIN + (CONTENT_WIDTH - 20) / 2 + 40,
          y: 280,
          width: (CONTENT_WIDTH - 20) / 2 - 40,
          height: 120,
          textStyle: {
            fontFamily: "Inter",
            fontSize: 10.5,
            fontWeight: 400,
            lineHeight: 1.5,
            color: "#334155",
          },
        },
        // Quadrant 3 (bottom-left)
        {
          id: "fs-card3-bg",
          type: "shape",
          shape: "rounded",
          x: MARGIN,
          y: 450,
          width: (CONTENT_WIDTH - 20) / 2,
          height: 220,
          fill: { color: "#f8fafc" },
          stroke: { color: "#e2e8f0" },
          strokeWidth: 1,
        },
        {
          id: "fs-card3-val",
          type: "text",
          slotId: "stat3-value",
          x: MARGIN + 20,
          y: 470,
          width: (CONTENT_WIDTH - 20) / 2 - 40,
          height: 48,
          textStyle: {
            fontFamily: "Playfair Display",
            fontSize: 34,
            fontWeight: 700,
            color: "#2563eb",
          },
        },
        {
          id: "fs-card3-desc",
          type: "text",
          slotId: "stat3-desc",
          x: MARGIN + 20,
          y: 526,
          width: (CONTENT_WIDTH - 20) / 2 - 40,
          height: 120,
          textStyle: {
            fontFamily: "Inter",
            fontSize: 10.5,
            fontWeight: 400,
            lineHeight: 1.5,
            color: "#334155",
          },
        },
        // Quadrant 4 (bottom-right)
        {
          id: "fs-card4-bg",
          type: "shape",
          shape: "rounded",
          x: MARGIN + (CONTENT_WIDTH - 20) / 2 + 20,
          y: 450,
          width: (CONTENT_WIDTH - 20) / 2,
          height: 220,
          fill: { color: "#f8fafc" },
          stroke: { color: "#e2e8f0" },
          strokeWidth: 1,
        },
        {
          id: "fs-card4-val",
          type: "text",
          slotId: "stat4-value",
          x: MARGIN + (CONTENT_WIDTH - 20) / 2 + 40,
          y: 470,
          width: (CONTENT_WIDTH - 20) / 2 - 40,
          height: 48,
          textStyle: {
            fontFamily: "Playfair Display",
            fontSize: 34,
            fontWeight: 700,
            color: "#2563eb",
          },
        },
        {
          id: "fs-card4-desc",
          type: "text",
          slotId: "stat4-desc",
          x: MARGIN + (CONTENT_WIDTH - 20) / 2 + 40,
          y: 526,
          width: (CONTENT_WIDTH - 20) / 2 - 40,
          height: 120,
          textStyle: {
            fontFamily: "Inter",
            fontSize: 10.5,
            fontWeight: 400,
            lineHeight: 1.5,
            color: "#334155",
          },
        },
      ],
    },

    // 8. Quote Feature
    {
      id: "quote-feature",
      name: "Pull Quote Feature",
      role: "quote",
      fallbackLayouts: ["heading-body"],
      slots: [
        {
          id: "kicker",
          name: "Section Eyebrow",
          role: "kicker",
          accepts: ["caption", "metadata", "unknown", "heading"],
          required: false,
          maxCharacters: 60,
        },
        {
          id: "quote",
          name: "Pull Quote Text",
          role: "quote",
          accepts: ["quote", "paragraph"],
          required: true,
          maxCharacters: 350,
        },
        {
          id: "attribution",
          name: "Attribution / Author",
          role: "attribution",
          accepts: ["caption", "paragraph", "metadata", "unknown"],
          required: false,
          maxCharacters: 120,
        },
        {
          id: "supporting-body",
          name: "Supporting Commentary",
          role: "body",
          accepts: ["paragraph", "callout"],
          required: false,
          maxCharacters: 900,
        },
      ],
      baseElements: [
        {
          id: "qf-kicker",
          type: "text",
          slotId: "kicker",
          x: MARGIN,
          y: 72,
          width: CONTENT_WIDTH,
          height: 24,
          textStyle: {
            fontFamily: "Inter",
            fontSize: 11,
            fontWeight: 600,
            color: "#2563eb",
            letterSpacing: 1.5,
          },
        },
        // Large Quote Box
        {
          id: "qf-card-bg",
          type: "shape",
          shape: "rounded",
          x: MARGIN,
          y: 110,
          width: CONTENT_WIDTH,
          height: 280,
          fill: { color: "#f8fafc" },
          stroke: { color: "#e2e8f0" },
          strokeWidth: 1,
        },
        // Quotation mark icon/shape
        {
          id: "qf-quote-bar",
          type: "shape",
          shape: "rectangle",
          x: MARGIN + 30,
          y: 150,
          width: 4,
          height: 180,
          fill: { color: "#2563eb" },
        },
        {
          id: "qf-quote-text",
          type: "text",
          slotId: "quote",
          x: MARGIN + 50,
          y: 146,
          width: CONTENT_WIDTH - 90,
          height: 160,
          constraints: {
            minFontSize: 14,
            maxFontSize: 24,
            allowResize: true,
          },
          textStyle: {
            fontFamily: "Playfair Display",
            fontSize: 20,
            fontWeight: 500,
            lineHeight: 1.45,
            color: "#0f172a",
          },
        },
        {
          id: "qf-attr",
          type: "text",
          slotId: "attribution",
          x: MARGIN + 50,
          y: 320,
          width: CONTENT_WIDTH - 90,
          height: 36,
          textStyle: {
            fontFamily: "Inter",
            fontSize: 11,
            fontWeight: 600,
            color: "#64748b",
          },
        },
        // Supporting body below
        {
          id: "qf-body",
          type: "text",
          slotId: "supporting-body",
          x: MARGIN,
          y: 420,
          width: CONTENT_WIDTH,
          height: 290,
          constraints: {
            minFontSize: 9.5,
            maxFontSize: 12,
            allowResize: true,
          },
          textStyle: {
            fontFamily: "Inter",
            fontSize: 11,
            fontWeight: 400,
            lineHeight: 1.6,
            color: "#334155",
          },
        },
      ],
    },

    // 9. Table Page
    {
      id: "table-page",
      name: "Structured Data Table",
      role: "table",
      fallbackLayouts: ["heading-body"],
      slots: [
        {
          id: "heading",
          name: "Table Heading",
          role: "heading",
          accepts: ["heading", "subheading"],
          required: true,
          maxCharacters: 120,
        },
        {
          id: "intro",
          name: "Table Commentary",
          role: "body",
          accepts: ["paragraph", "callout"],
          required: false,
          maxCharacters: 400,
        },
        {
          id: "table",
          name: "Data Table",
          role: "table",
          accepts: ["table", "table_row"],
          required: true,
        },
        {
          id: "caption",
          name: "Source / Notes",
          role: "caption",
          accepts: ["caption", "metadata", "paragraph", "unknown"],
          required: false,
          maxCharacters: 200,
        },
      ],
      baseElements: [
        {
          id: "tp-heading",
          type: "text",
          slotId: "heading",
          x: MARGIN,
          y: 72,
          width: CONTENT_WIDTH,
          height: 52,
          textStyle: {
            fontFamily: "Playfair Display",
            fontSize: 22,
            fontWeight: 700,
            lineHeight: 1.3,
            color: "#0f172a",
          },
        },
        {
          id: "tp-intro",
          type: "text",
          slotId: "intro",
          x: MARGIN,
          y: 130,
          width: CONTENT_WIDTH,
          height: 56,
          textStyle: {
            fontFamily: "Inter",
            fontSize: 11,
            fontWeight: 400,
            lineHeight: 1.5,
            color: "#475569",
          },
        },
        {
          id: "tp-table",
          type: "table",
          slotId: "table",
          x: MARGIN,
          y: 198,
          width: CONTENT_WIDTH,
          height: 480,
          columns: 3,
          headerRows: 1,
          rows: [],
        },
        {
          id: "tp-caption",
          type: "text",
          slotId: "caption",
          x: MARGIN,
          y: 695,
          width: CONTENT_WIDTH,
          height: 30,
          textStyle: {
            fontFamily: "Inter",
            fontSize: 9,
            fontWeight: 400,
            color: "#64748b",
          },
        },
      ],
    },

    // 10. Chart + Commentary
    {
      id: "chart-commentary",
      name: "Chart & Commentary",
      role: "chart",
      fallbackLayouts: ["table-page", "heading-body"],
      slots: [
        {
          id: "heading",
          name: "Chart Heading",
          role: "heading",
          accepts: ["heading", "subheading"],
          required: true,
          maxCharacters: 120,
        },
        {
          id: "chart",
          name: "Chart Visual",
          role: "chart",
          accepts: ["table", "table_row", "statistic", "unknown"],
          required: false,
        },
        {
          id: "commentary",
          name: "Key Takeaways & Analysis",
          role: "body",
          accepts: ["paragraph", "callout", "list_item"],
          required: true,
          maxCharacters: 900,
        },
        {
          id: "source-note",
          name: "Data Source",
          role: "caption",
          accepts: ["caption", "metadata", "unknown"],
          required: false,
          maxCharacters: 140,
        },
      ],
      baseElements: [
        {
          id: "cc-heading",
          type: "text",
          slotId: "heading",
          x: MARGIN,
          y: 72,
          width: CONTENT_WIDTH,
          height: 52,
          textStyle: {
            fontFamily: "Playfair Display",
            fontSize: 22,
            fontWeight: 700,
            lineHeight: 1.3,
            color: "#0f172a",
          },
        },
        {
          id: "cc-chart",
          type: "chart",
          slotId: "chart",
          x: MARGIN,
          y: 136,
          width: CONTENT_WIDTH,
          height: 280,
          chartType: "bar",
          labels: ["Metric A", "Metric B", "Metric C"],
          data: [65, 82, 94],
          title: "Comparative Performance",
        },
        {
          id: "cc-commentary",
          type: "text",
          slotId: "commentary",
          x: MARGIN,
          y: 440,
          width: CONTENT_WIDTH,
          height: 238,
          constraints: {
            minFontSize: 9.5,
            maxFontSize: 12,
            allowResize: true,
          },
          textStyle: {
            fontFamily: "Inter",
            fontSize: 10.5,
            fontWeight: 400,
            lineHeight: 1.55,
            color: "#334155",
          },
        },
        {
          id: "cc-source",
          type: "text",
          slotId: "source-note",
          x: MARGIN,
          y: 694,
          width: CONTENT_WIDTH,
          height: 26,
          textStyle: {
            fontFamily: "Inter",
            fontSize: 9,
            fontWeight: 400,
            color: "#94a3b8",
          },
        },
      ],
    },

    // 11. Closing
    {
      id: "closing",
      name: "Summary & Conclusion",
      role: "closing",
      fallbackLayouts: ["heading-body"],
      slots: [
        {
          id: "heading",
          name: "Closing Heading",
          role: "heading",
          accepts: ["heading", "subheading"],
          required: true,
          maxCharacters: 120,
        },
        {
          id: "conclusion",
          name: "Conclusion Copy",
          role: "body",
          accepts: ["paragraph", "callout", "list_item"],
          required: true,
          maxCharacters: 1200,
        },
        {
          id: "next-steps",
          name: "Next Steps / Call to Action",
          role: "body",
          accepts: ["cta", "paragraph", "list_item"],
          required: false,
          maxCharacters: 400,
        },
        {
          id: "sign-off",
          name: "Sign-off / Contact",
          role: "attribution",
          accepts: ["metadata", "caption", "paragraph", "unknown"],
          required: false,
          maxCharacters: 180,
        },
      ],
      baseElements: [
        {
          id: "cl-heading",
          type: "text",
          slotId: "heading",
          x: MARGIN,
          y: 90,
          width: CONTENT_WIDTH,
          height: 56,
          textStyle: {
            fontFamily: "Playfair Display",
            fontSize: 26,
            fontWeight: 700,
            lineHeight: 1.25,
            color: "#0f172a",
          },
        },
        {
          id: "cl-divider",
          type: "shape",
          shape: "line",
          x: MARGIN,
          y: 154,
          width: CONTENT_WIDTH,
          height: 1,
          stroke: { color: "#2563eb" },
          strokeWidth: 2,
        },
        {
          id: "cl-conclusion",
          type: "text",
          slotId: "conclusion",
          x: MARGIN,
          y: 176,
          width: CONTENT_WIDTH,
          height: 260,
          constraints: {
            minFontSize: 10,
            maxFontSize: 13,
            allowResize: true,
          },
          textStyle: {
            fontFamily: "Inter",
            fontSize: 11,
            fontWeight: 400,
            lineHeight: 1.6,
            color: "#334155",
          },
        },
        {
          id: "cl-cta-card",
          type: "shape",
          shape: "rounded",
          x: MARGIN,
          y: 456,
          width: CONTENT_WIDTH,
          height: 140,
          fill: { color: "#f8fafc" },
          stroke: { color: "#e2e8f0" },
          strokeWidth: 1,
        },
        {
          id: "cl-next-steps",
          type: "text",
          slotId: "next-steps",
          x: MARGIN + 24,
          y: 480,
          width: CONTENT_WIDTH - 48,
          height: 98,
          textStyle: {
            fontFamily: "Inter",
            fontSize: 10.5,
            fontWeight: 400,
            lineHeight: 1.5,
            color: "#334155",
          },
        },
        {
          id: "cl-signoff",
          type: "text",
          slotId: "sign-off",
          x: MARGIN,
          y: 636,
          width: CONTENT_WIDTH,
          height: 60,
          textStyle: {
            fontFamily: "Inter",
            fontSize: 10,
            fontWeight: 500,
            color: "#64748b",
            lineHeight: 1.4,
          },
        },
      ],
    },

    // 12. Text Continuation
    {
      id: "text-continuation",
      name: "Continued Text",
      role: "content",
      description:
        "Continuation layout for body copy too large for its original page.",
      slots: [],
      baseElements: [
        {
          id: "ctc-body",
          type: "text",
          x: MARGIN,
          y: 72,
          width: CONTENT_WIDTH,
          height: 666,
          constraints: {
            minFontSize: 9.5,
            maxFontSize: 13,
            allowReflow: true,
            allowResize: true,
          },
          textStyle: {
            fontFamily: "Inter",
            fontSize: 11,
            fontWeight: 400,
            lineHeight: 1.6,
            color: "#334155",
          },
        },
      ],
    },

    // 13. Table Continuation
    {
      id: "table-continuation",
      name: "Continued Table",
      role: "table",
      description: "Continuation layout for tables split by rows across pages.",
      slots: [],
      baseElements: [
        {
          id: "ctt-table",
          type: "table",
          x: MARGIN,
          y: 72,
          width: CONTENT_WIDTH,
          height: 660,
          columns: 3,
          headerRows: 1,
          rows: [],
        },
      ],
    },
  ],
};
